//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _3250457_circular_silver_metal_background {
            get {
                object obj = ResourceManager.GetObject("3250457-circular-silver-metal-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3271946_brushed_smooth_glossy_metal_surface_texture_background_illustration {
            get {
                object obj = ResourceManager.GetObject("3271946-brushed-smooth-glossy-metal-surface-texture-background-illustration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3479780_polished_metal_abstract_background_texture_with_smoothening {
            get {
                object obj = ResourceManager.GetObject("3479780-polished-metal-abstract-background-texture-with-smoothening", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8645787_brushed_silver_metallic_background {
            get {
                object obj = ResourceManager.GetObject("8645787-brushed-silver-metallic-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8768235_metal_surface {
            get {
                object obj = ResourceManager.GetObject("8768235-metal-surface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _9185216_brushed_silver_metallic_background {
            get {
                object obj = ResourceManager.GetObject("9185216-brushed-silver-metallic-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aluminium_brushed_metal_background_texture_hd_575x400 {
            get {
                object obj = ResourceManager.GetObject("aluminium-brushed-metal-background-texture-hd-575x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b10metals009 {
            get {
                object obj = ResourceManager.GetObject("b10metals009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brushed_silver_metallic_background_pic {
            get {
                object obj = ResourceManager.GetObject("brushed-silver-metallic-background-pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_cancel {
            get {
                object obj = ResourceManager.GetObject("button_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_cancelOff {
            get {
                object obj = ResourceManager.GetObject("button_cancelOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap christmas_tree_metallic_blue {
            get {
                object obj = ResourceManager.GetObject("christmas-tree-metallic-blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hospitalera080500023 {
            get {
                object obj = ResourceManager.GetObject("hospitalera080500023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap metal_plate_color_background_texture_e {
            get {
                object obj = ResourceManager.GetObject("metal-plate-color-background-texture-e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Metal_Texture_by_AllydNYC {
            get {
                object obj = ResourceManager.GetObject("Metal_Texture_by_AllydNYC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Metal_Texture_PLUS_Metal_Grid {
            get {
                object obj = ResourceManager.GetObject("Metal_Texture_PLUS_Metal_Grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap metal4 {
            get {
                object obj = ResourceManager.GetObject("metal4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetallicSilver {
            get {
                object obj = ResourceManager.GetObject("MetallicSilver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mfjS7JW {
            get {
                object obj = ResourceManager.GetObject("mfjS7JW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap seamlesstexture_metallic {
            get {
                object obj = ResourceManager.GetObject("seamlesstexture_metallic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
